<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<RootNamespace>Edemly.Client</RootNamespace>
		<AssemblyName>Edemly.Client</AssemblyName>
		<ApplicationIcon>Assets\Branding\app-icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Assets\**" Exclude="Assets\Unused\**" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Remove="Assets\Audio\message-notification.wav" />
	  <Resource Remove="Assets\Audio\call-ringtone.wav" />
	  <Resource Remove="Assets\Audio\call-ended.wav" />
	  <Resource Remove="Assets\Audio\call-dialing.wav" />
	  <Resource Remove="Assets\Audio\call-countdown.wav" />
	  <Resource Remove="Assets\Localization\*.json" />
	  <Resource Remove="Assets\Legal\*.txt" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Assets\Localization\*.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Legal\*.txt">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Audio\message-notification.wav">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Audio\call-ringtone.wav">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Audio\call-ended.wav">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Audio\call-dialing.wav">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Audio\call-countdown.wav">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Branding\app-icon.ico">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\Stickers\**">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Concentus" Version="2.2.2" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.8" />

		<PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />

		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1587.40" />

		<PackageReference Include="NAudio" Version="2.2.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Edemly.Contracts\Edemly.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Presentation\Resources\Styles\" />
	</ItemGroup>

</Project>
